name: ci

on:
  push:
    branches: main

jobs:
  test_github_action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        CUDA: [11.6]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CUDA
      uses: nvidia/setup-cuda@v1
      with:
        cuda-version: ${{ matrix.CUDA }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests with GPU
      run: python test_torch.py  # 这里应该是你的测试命令