name: ci

on:
  push:
    branches: main

jobs:
  test_github_action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        CUDA: [11.6]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install NVIDIA driver
      run: |
        sudo apt-get update -q
        sudo apt-get install -y nvidia-driver-450
        sudo nvidia-smi -L

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests with GPU
      run: python test_torch.py  # 这里应该是你的测试命令